### ISSUE TITLE
Drop git submodules

### ISSUE THREAD

**Issue by bmschmidt** [senderle/bookworm-compose#16]
Submodules are confusing. (https://github.com/senderle/bookworm-compose/issues/12). We just need to bundle the full code for included repositories or download them at a  particular hash from github.

Included modules are:
* BookwormDB
* Bookworm-Vega
* Bookworm-App

**Comment by senderle** [comment]
Yes, it feels like submodules should just work here — we are having to do too much plumbing.

If we went the download route, could we package it into a `bin/run` command?

**Comment by bmschmidt** [comment]
I'm setting it up to just clone the full git repo into a folder called `/lib`. It's nice to be able to edit in place.  At some will have to do a little work to keep the full git history from living in the container, but I think it's OK for developers to have it locally.

**Comment by bmschmidt** [comment]
Fixed https://github.com/senderle/bookworm-compose/commit/2dfca7985edb06846ee675a00a1dfcef3e2f92fe
