### ISSUE TITLE
Traefik-optional architecture

### ISSUE THREAD

**Issue by bmschmidt** [senderle/bookworm-compose#8]
Here's a different architecture worth considering, I think. The goal here is that I'd like to be able to run this service anywhere. But it's especially important right now that it work on local machines as well as in the cloud, and traefik seems to be making that harder.

1. ssl encryption is tricky, but is also not critical. There may be cases where, even while using docker, another ssl solution is more appropriate. So if you want ssl, you've got to run `docker-compose -f docker-compose.yml -f docker-compose-ssl.yml`.
2. Currently traefik handles the proxy of `/cgi-bin*` -> `remote:10012/*` to manage API queries. This kind of passthrough is a core feature of any webserver; wouldn't it be best to have nginx handle it directly. Brief browsing suggests that injecting a configuration file into nginx might require a custom image. In development cases, you probably want to do something like `docker-compose -f docker-compose.yml -f docker-compose-dev.yml`, which will map nginx's `0.0.0.0:8080:80` so that a non-superuser can look at web pages on their local machine. (If it's preferable to have traefik do the remapping without by default including all sorts of ssl mishegas, that's fine.)
3. The core `docker-compose.yml` should contain no personal credentials and nothing that invokes personal credentials; should include an unsafe mysql root password so that it can just run for unit testing without needing anything other; and should contain nothing that explicitly names output ports on the host machine, or at least output ports below 1024, since you can't assume superuser access.

**Comment by senderle** [comment]
The docker-provider branch should be working on localhost with the default docker-compose.yml now. If it doesn't work, try removing all existing traefik images — one of the previous builds had a config file built in that no longer works.

**Comment by senderle** [comment]
Huh, wonder why I don't have that problem. Well anyway, yeah, it's dumb to be serving on 80, sorry I'll fix that!

**Comment by senderle** [comment]
Oh, somehow I reverted the change from my test server to localhost. Restored that and set things up to serve on :8000. Let me know if it still doesn't work!

**Comment by bmschmidt** [comment]
I've just pushed this all to main, because that branch was just stale, and have deleted the docker-compose branch. I'm leaving some traefik boilerplate in there because it doesn't break anything, but will not touch it.
