### ISSUE TITLE
Properly link services over internal ports.

### ISSUE THREAD

**Issue by bmschmidt** [senderle/bookworm-compose#9]
I mostly got the nginx configuration running, but there's something funky about the proxy passthrough.

I've tried--twice, in both dockerfile and docker.compose.yml!--to EXPOSE port 10012 from the bookworm serve inside the network. But it seems to be invisible from inside the nginx container at `http://bookworm:10012`. This isn't just nginx: from inside the nginx container, curl `bookworm:10012/` returns `curl: (7) Failed to connect to localhost port 10012: Connection refused`. The inverse isn't true: from inside the bookworm container, `curl http://nginx` gives the contents of `index.html`. So I'm stumped for now.

Clearly I'm not understanding something basic, and this will only get worse when mariadb comes into the mix.

**Comment by senderle** [comment]
Hmm, which branch is this on? I haven't ever needed to use an EXPOSE directive in a Dockerfile — in my (still limited) experience, ports are usually exposed as a part of a `docker run` command or in a compose file?

**Comment by senderle** [comment]
Ah I see — so this is related to changes committed to docker-provider, yes? There should actually be no need to expose the mariadb port at all — or at least I've never had to expose ports for internal use. It's serving on the standard MySQL port, so it should be enough to use the service name as the url in the config for BookwormDB.

**Comment by senderle** [comment]
Just for the sake of not stepping on each others' toes, I split off a branch with the previous state of docker-provider, which I'll continue to update as I learn more about what needs to happen with BookwormDB, etc. This will make it easier to compare the two approaches.

**Comment by bmschmidt** [comment]
Good if mariadb won't be an issue.

The issue that's completely blocking me is that the service we're running as a python process (through `bookworm serve`) isn't accessible from the other containers at the location I'd expect it (`http://bookworm:10012`).

This is true inside the nginx container. My understanding of docker-compose is that, if the process is running on port 10012 inside the bookworm container, we should be able to get from inside the nginx one.

```
(base) ➜  git:(master) ✗ docker exec -it bookworm-compose_nginx_1 /usr/bin/curl localhost:80
<h3>Bookworm</h3><ul><li>Linecharts</li></ul>
(base) ➜  git:(master) ✗ docker exec -it bookworm-compose_nginx_1 /usr/bin/curl bookworm:10012 
curl: (7) Failed to connect to bookworm port 10012: Connection refused
```

**Comment by senderle** [comment]
Yeah strong agree, that's weird and shouldn't be happening. When I run with the test flask server I set up, everything works as expected. Have you checked to see whether the dummy flask server works when you change `bookworm serve` to `gunicorn --bind 0.0.0.0:10012 bookworm:app` in the `docker-compose.yml` file?

That's the only thing I've been using for testing, since I haven't been sure how to get `bookworm serve` fully operational. And it seems to work as expected? If it works for you as well then I'm at a loss, but I can only assume it has something to do with the way BookwormDB is configured?

**Comment by senderle** [comment]
On another note, I'm realizing that really fundamentally your branch is going to be the get-bookworm-working branch, and my branch is going to be the get-production-ready-ssl-support-etc branch. And then we can merge them. It makes sense on my branch for even local dev to use traefik but in the final end-product probably the local dev setup will just use nginx. Seem like a good division of labor to you?

**Comment by bmschmidt** [comment]
OK, your question shook loose the answer--I was binding the bookworm service to 127.0.0.1, but actually needed to bind to 0.0.0.0 for it to be accessible from the other containers. That bit is working now, including the passthrough from nginx at /cgi-bin. (IE., localhost:8020/index gives something from nginx, localhost:8020/cgi-bin goes to bookworm.)

On division--I'm pretty sure looking at the current state that I'll never figure out of the mariadb configuration with my understanding of docker. Would love if we could figure that out before worrying about ssl config.

**Comment by senderle** [comment]
Ah, that makes sense! 

No problem re:mariadb, etc. I'll pause on the SSL then. Let's coordinate at 11!
